#!/usr/bin/env node

import * as fs from 'fs';
import { NotionNextJSConfig } from '../types';

const CONFIG_FILENAME = 'notion.config.js';

function promptUser(question: string): Promise<string> {
	return new Promise((resolve) => {
		process.stdout.write(question + ' ');
		process.stdin.setEncoding('utf8');
		process.stdin.once('data', (data) => {
			resolve(data.toString().trim());
		});
	});
}

async function setup() {
	console.log('\n🚀 Welcome to notion-nextjs setup!\n');

	// Check if config already exists
	if (fs.existsSync(CONFIG_FILENAME)) {
		const overwrite = await promptUser('Config file already exists. Overwrite? (y/N):');
		if (overwrite.toLowerCase() !== 'y') {
			console.log('Setup cancelled.');
			process.exit(0);
		}
	}

	// Collect database information
	const databases: Record<string, string> = {};
	console.log('Enter your Notion database information:\n');

	let isFirstDatabase = true;
	while (true) {
		const prompt = isFirstDatabase ? 'Database name (e.g., "blog"):' : 'Database name (or press Enter to finish):';

		const name = await promptUser(prompt);
		if (!name) break;

		const id = await promptUser('Database ID:');
		if (!id) {
			console.log('Database ID is required. Skipping this database.\n');
			continue;
		}

		databases[name] = id;
		console.log(`✅ Added database "${name}"\n`);
		isFirstDatabase = false;
	}

	if (Object.keys(databases).length === 0) {
		console.log('No databases configured. Setup cancelled.');
		process.exit(1);
	}

	// Ask about additional options
	const enableImages = await promptUser('Enable image optimization? (Y/n):');
	const useLocalCache = await promptUser('Enable local caching? (Y/n):');

	// Create configuration
	const config: NotionNextJSConfig = {
		databases,
		dataSource: useLocalCache.toLowerCase() === 'n' ? 'live' : 'local',
	};

	if (enableImages.toLowerCase() !== 'n') {
		config.images = {
			enabled: true,
			outputDir: '/public/images/notion',
			format: 'webp',
			quality: 85,
		};
	}

	if (config.dataSource === 'local') {
		config.outputDir = '.notion-cache';
	}

	// Generate config file content
	const configContent = `// notion.config.js
// Generated by notion-nextjs

/** @type {import('notion-nextjs').NotionNextJSConfig} */
module.exports = {
  databases: ${JSON.stringify(databases, null, 4).replace(/\n/g, '\n  ')},
  dataSource: '${config.dataSource}',
${config.outputDir ? `  outputDir: '${config.outputDir}',\n` : ''}${
		config.images
			? `  images: {
    enabled: ${config.images.enabled},
    outputDir: '${config.images.outputDir}',
    format: '${config.images.format}',
    quality: ${config.images.quality},
  },\n`
			: ''
	}};
`;

	// Write config file
	fs.writeFileSync(CONFIG_FILENAME, configContent);
	console.log(`\n✅ Created ${CONFIG_FILENAME}`);

	// Create .env.local template if it doesn't exist
	const envPath = '.env.local';
	if (!fs.existsSync(envPath)) {
		const envContent = `# Notion API Configuration
NOTION_API_KEY=your-notion-integration-token-here
`;
		fs.writeFileSync(envPath, envContent);
		console.log(`✅ Created ${envPath} template`);
	}

	// Show next steps
	console.log('\n📝 Next steps:');
	console.log('1. Add your Notion API key to .env.local');
	console.log('2. Import and use notion-nextjs in your project:');
	console.log('\n   ```typescript');
	console.log('   import { NotionNextJS } from "notion-nextjs";');
	console.log('   import config from "./notion.config.js";');
	console.log('');
	console.log('   const notion = new NotionNextJS(process.env.NOTION_API_KEY!, config);');
	console.log('   const pages = await notion.getAllPages<YourType>("blog");');
	console.log('   ```\n');

	process.exit(0);
}

async function main() {
	const command = process.argv[2];

	switch (command) {
		case 'setup':
			await setup();
			break;
		case 'sync':
			console.log('Sync command coming soon!');
			break;
		default:
			console.log('notion-nextjs CLI\n');
			console.log('Commands:');
			console.log('  setup  - Initialize notion-nextjs configuration');
			console.log('  sync   - Sync data and generate types (coming soon)');
			break;
	}
}

// Handle errors
process.on('uncaughtException', (error) => {
	console.error('\n❌ Error:', error.message);
	process.exit(1);
});

main();
