// Generated by notion-nextjs
// Do not edit manually - run "npx notion-nextjs sync" to update

import type { SimplifiedPage } from 'notion-nextjs';

export interface BlogPage extends SimplifiedPage {
	/**
	 * Property name mapping:
	 * - "Subtitle" → subtitle
	 * - "Publish Date" → publishDate
	 * - "Status" → status
	 * - "Title" → title
	 */
	// Override properties with specific types for this database
	simplifiedProperties: {
		subtitle: string;
		publishDate: string | null;
		status: string | null;
		title: string;
	};
}
