// Generated by notion-nextjs
// Do not edit manually - run "npx notion-nextjs sync" to update

import type { SimplifiedPage } from 'notion-nextjs';

export interface BlogPage extends SimplifiedPage {
  // Override properties with specific types for this database
  simplifiedProperties: {
    Subtitle: string;
    Date: string | null;
    Status: string | null;
    Title: string;
  };
}