// Generated by notion-nextjs
// Do not edit manually - run "npx notion-nextjs sync" to update

import type { SimplifiedPage } from 'notion-nextjs';

export interface BlogPage extends SimplifiedPage {
  /**
   * Property name mapping:
   * - "Subtitle" → subtitle
   * - "Publish Date" → publishDate
   * - "Status" → status
   * - "Title" → title
   */
 
  simplifiedProperties: {
    subtitle: string;
    publishDate: string | null;
    status: string | null;
    title: string;
  };
}

export interface DocsPage extends SimplifiedPage {
  /**
   * Property name mapping:
   * - "Name" → name
   */
 
  simplifiedProperties: {
    name: string;
  };
}