// notion.config.js
// Generated by notion-nextjs

/** @type {import('notion-nextjs').NotionNextJSConfig} */
module.exports = {
  databases: {
      "blog": "20d58a3245d4804cb212e01b595be565"
  },
  dataSource: 'local',
  outputDir: '.notion-cache',
  images: {
    enabled: true,
    outputDir: '/public/images/notion',
    format: 'webp',
    quality: 85,
  },
};
